version: "3.8"
services:
#    apache:
#        container_name: apache
#        build: ./docker/apache
#        links:
#            - php
#        ports:
#            - "8080:80"
#        volumes:
#            - ./logs/apache:/var/log/apache2
#            - ./src/helloworld:/usr/local/apache2/htdocs/helloworld
#    php:
#        container_name: php
#        build: ./docker/php
#        links:
#            - mongo
#        ports:
#            - "9000:9000"
#        volumes:
#            - ./src/helloworld:/usr/local/apache2/htdocs/helloworld
#        working_dir: /usr/local/apache2/htdocs/helloworld
#    composer:
#        container_name: composer
#        image: composer/composer
#        volumes:
#            - ./src/helloworld:/usr/local/apache2/htdocs/helloworld
#        working_dir: /usr/local/apache2/htdocs/helloworld
#        command: install
    mongo:
        image: mongo:4.2
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        restart: unless-stopped
        ports:
            - "37017:27017"
        volumes:
            - ./database/mongodb/db:/data/db
            - ./database/mongodb/dev.archive:/Databases/dev.archive
            - ./database/mongodb/production:/Databases/production
        command: [--auth]
    mongo-express:
        image: mongo-express
        container_name: mexpress
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
            - ME_CONFIG_BASICAUTH_USERNAME=mexpress
            - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
        links:
            - mongo
        restart: unless-stopped
        ports:
            - "8081:8081"
#    mysql:
#        image: mysql:8.0.27
#        container_name: mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: 'password'
#            MYSQL_DATABASE: helloworld
#            MYSQL_USER: helloworld
#            MYSQL_PASSWORD: 'password'
#        ports:
#            - "3306:3306"
#        volumes:
#            - ./database/mysql:/var/lib/mysql
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: pma
#        links:
#            - mysql
#        environment:
#            PMA_HOST: mysql
#            PMA_PORT: 3306
#            PMA_ARBITRARY: 1
#        restart: always
#        ports:
#            - 8085:80
